apiVersion: apps/v1
kind: Deployment
metadata:
  name: accommodation
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accommodation
  template:
    metadata:
      labels:
        app: accommodation
    spec:
      containers:
        - name: springboot-container
          image: rahmafira/accommodation:REPLACE_ME_TAG
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL_PROD
              valueFrom:
                configMapKeyRef:
                  name: accommodation-config
                  key: DATABASE_URL_PROD
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: accommodation-config
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accommodation-secret
                  key: DATABASE_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: accommodation-secret
                  key: JWT_SECRET_KEY